# Inspired by https://github.com/bitbrain/beehave/blob/godot-4.x/.github/workflows/beehave-ci.yml

name: Mod Loader CI

on:
  push:
    paths-ignore:
      - "**.jpg"
      - "**.png"
      - "**.svg"
      - "**.md"
      - "**plugin.cfg"
  pull_request:
    paths-ignore:
      - "**.jpg"
      - "**.png"
      - "**.svg"
      - "**.md"
      - "**plugin.cfg"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "Running GUT tests on Godot 4.3"
    uses: ./.github/workflows/tests.yml
    with:
      godot-version: "4.3"
